### ISSUE TITLE
Setup EM

### ISSUE THREAD

**Issue by VrankenKris** [Sciensano-Healthdata/HD-Corona#252]

**Comment by TimDM1980** [comment]
Tasks:
- [x] Configure CVD-P-EM01
- [x] Configure CVD-P-POST01
- [ ] Configure for local logs storage instead of Cloudwatch
- [ ] Create read only user for DWH (+ document this)

Blocked:
- [ ] Install ACC cert and configure EM for ACC (env, p12 filename, password)
- [ ] Test we can receive a message on ACC
- [ ] Install PRD cert and configure EM for PRD
- [ ] Test we can receive a message on PRD
- [ ] Test 4 dataflows and 2 data formats (JSON, CSV)

**Comment by TimDM1980** [comment]
Encrypted VS Unencrypted

How will other parties send data to our EM?
Encrypted or unencrypted?

If it's encrypted:
- then the sender will have to include `"metadata": { "[ttp_project]": "FOOBAR" }` in the ehealth message, or our EM won't be able to decrypt the message, unless we make a code change

If it's unencrypted:
- then Juan needs to read from the ehealth_incoming_message table
- then we need to make a change to our application in order to be able to send unencrypted test messages

**Comment by VrankenKris** [comment]
We kunnen zelf unencrypted messages sturen vanuit SAS.
We zullen vragen om unencrypted via eHBox te sturen.

Kris Vranken
Technical Lead
Healthdata.be
M + 32 491 08 02 05
Skype kriswiv
[cid:image002.jpg@01D5962C.5D529BC0]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

P  Please consider the environment before printing this e-mail
