### ISSUE TITLE
Data Model in HD DWH environement

### ISSUE THREAD

**Issue by helene-ameels** [Sciensano-Healthdata/HD-Corona#323]
DWH to prepare the HD DWH environement for the reception of  the historical data and new data for the following lime surveys:
- ADMISSION
- DISCHARGE
- INTENSIVE CARE UNIT (ICU)

Codebook provide by client for Admission and Discharge
https://www.dropbox.com/scl/fi/2hccmuuhw3nsnojd5gez0/List_variables_names-values_2020_06_10.xlsx?dl=0&rlkey=zm48rfhrzrnhj7nh3k24vwylq

ICU under development by Nikita based on excel file provided by client: https://www.dropbox.com/scl/fi/w4z7g5i45d0noymx8zgjf/ICU_supplement_20_06.22_for_HD.xlsx?dl=0&rlkey=j082x0sc61nlwhwd6sq3u2ntm

Rmq:
- Addition of INSS in the 3 limesurvey required
- Additional possible answers for the question ‘Expo_collective_housing’ (in admission survey)

1. EN: Yes, other elderly housing /FR: Oui, Autre collectivité résidentielle pour personnes âgées (Résidence-services, seigneurie, …) / NL: Ja, Andere woongemeenschap voor ouderen (assistentiewoning, seniorie, service flat) 
2. EN: Yes, disability institution /FR: Oui, Institution pour personnes handicapées /NL: Ja, Instelling voor personen met een handicap

**Comment by helene-ameels** [comment]
To be managed via DWH Zenhub board --> @VrankenKris  - to follow up with DWH

**Comment by PietOlivierSciensano** [comment]
Analysis of Admission and Discharge Limesurveys to create according Filespecs started, 

Key Value table will be generated from the lime_survey_<survey_id> table.

This will facilitate the Load process into the Covid19 DB since alike procedures were
already developed for the Drupal project.

[https://app.zenhub.com/files/248791371/47e7a844-24aa-4cc7-8dbf-3c9576d3a5cc/download]
